---
bungeecord:
  build: bungeecord
  stdin_open: true
  tty: true
  ports:
  - 0.0.0.0:25565:25577
  volumes:
  - /opt/bungeecord:/opt/bungeecord
  links:
  - spigot
  restart: always
spigot:
  build: spigot
  stdin_open: true
  tty: true
  volumes:
  - /opt/minecraft:/opt/minecraft
  restart: always
consul:
  image: progrium/consul
  ports:
  - "8400:8400"
  - "8500:8500"
  - "8600:53"
  command: "-server -bootstrap-expect 3 -ui-dir /ui"
  
