---
bungeecord:
  build: bungeecord
  stdin_open: true
  tty: true
  ports:
  - 0.0.0.0:25565:25577
  volumes:
  - /opt/bungeecord:/opt/bungeecord
  links:
  - spigot
  restart: always
spigot:
  build: spigot
  stdin_open: true
  tty: true  
  ports:
  - "25566-26000:8500"
  volumes:
  - /opt/minecraft:/opt/minecraft
  restart: always
consul:
  image: gliderlabs/consul-server
  container_name: consul
  ports:
  - "0.0.0.0:8500:8500"
  - "8301:8301"
  - "8400:8400"
  command: "-bootstrap"
registrator:
  image: gliderlabs/registrator
  command: "-internal consul://consul:8500"
  container_name: 'registrator'
  links:
  - consul
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
