---
version: '2'
services:
  bungeecord:
    build: bungeecord
    stdin_open: true
    tty: true
    ports:
    - 25565:25577
    volumes:
    - /opt/bungeecord:/opt/bungeecord
    restart: always
  spigot:
    image: exorath/docker-spigot
    environment:
      SERVICE_NAME: spigot
    stdin_open: true
    tty: true  
    ports:
    - "25565"
    volumes:
    - /opt/minecraft:/opt/minecraft
    restart: always
  hub:
    extends:
      service: spigot
    environment:
      SERVICE_NAME: hub
  registrator:
    image: gliderlabs/registrator
    network_mode: host
    command: "-cleanup=true etcd://localhost:2379"
    container_name: registrator
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

