---
bungeecord:
  build: bungeecord
  stdin_open: true
  tty: true
  ports:
  - 0.0.0.0:25565:25565
  volumes:
  - /opt/bungeecord:/opt/bungeecord
  links:
  - spigot
  restart: always
spigot:
  build: spigot
  stdin_open: true
  tty: true
  volumes:
  - /opt/bungeecord:/opt/bungeecord
  restart: always
