---
version: '2'
services:
  bungeecord:
    build: bungeecord
    stdin_open: true
    tty: true
    ports:
    - 0.0.0.0:25565:25577
    volumes:
    - /opt/bungeecord:/opt/bungeecord
    restart: always
    links:
    - etcd
    - spigot
  spigot:
    image: exorath/docker-spigot
    environment:
      SERVICE_NAME: GAME=spigot
    stdin_open: true
    tty: true
    volumes:
    - /opt/minecraft:/opt/minecraft
    restart: always
  hub:
    extends:
      service: spigot
    environment:
      SERVICE_NAME: GAME=hub
  registrator:
    image: gliderlabs/registrator
    command: "--internal=true -cleanup=true etcd://etcd:2379"
    container_name: registrator
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    links:
    - etcd
  etcd:
    image: quay.io/coreos/etcd
    ports:
    - 127.0.0.1:2379:2379
    command: "-advertise-client-urls=http://etcd:2379 -listen-client-urls=http://0.0.0.0:2379"


